name: debarrioapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
#pe.acchiwan.debarrio
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  animated_splash_screen: ^1.1.0

  intro_slider: ^3.0.2

  intl: ^0.17.0

  google_fonts: ^2.1.0

  otp_text_field: ^1.1.1

  autocomplete_textfield: ^1.7.3

  carousel_slider: ^4.0.0

  modal_bottom_sheet: ^2.0.0

  #dropdown_formfield: ^0.1.3

  date_time_picker: ^2.1.0

  syncfusion_flutter_calendar: ^19.2.62

  google_maps_flutter: ^2.0.10

  flutter_svg: ^0.22.0

  location: ^4.3.0

  #hexcolor: ^1.0.6

  loading_overlay: ^0.3.0

  loading_indicator: ^3.0.2

  shared_preferences: ^2.0.8

  permission_handler: ^8.1.6

  firebase_auth: ^3.1.1

  #cloud_firestore: ^0.13.7

  firebase_storage: ^10.0.3

  #firebase_messaging: 6.0.15

  firebase_core: ^1.6.0

  #firebase_core: ^1.6.0

  #firebase_auth: ^3.1.1

  provider: ^6.0.1

  #geocoder: ^0.2.1

  flutter_geocoder: ^0.2.2-nullsafety

  uuid: ^3.0.4

  geodesy: ^0.4.0-nullsafety.0

  fluttertoast: ^8.0.8

  #auto_suggestion_text_field: ^0.1.1

  geolocator: ^7.6.2

  simple_autocomplete_formfield: ^0.3.0

  image_picker: ^0.8.4+2

  charcode: ^1.3.1

  #easy_loader: ^1.0.3

  dots_indicator: ^2.0.0

  sailor: ^0.7.1

  chopper: ^4.0.1

  #sms_autofill: ^1.2.5
  sms_autofill: ^2.1.2

  flutter_slidable: ^0.6.0

  flutter_search_bar: ^3.0.0-dev.1

  get_it: ^7.2.0

  flutter_credit_card:
    git:
      url: https://github.com/Dreadds/flutter_credit_card

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  weekday_selector: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  chopper_generator: ^4.0.2
  build_runner: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans_Regular.ttf
        - asset: fonts/OpenSans/OpenSans_Italic.ttf
        - asset: fonts/OpenSans/OpenSans_Bold.ttf
        - asset: fonts/OpenSans/OpenSans_Light.ttf
        - asset: fonts/OpenSans/OpenSans_SemiBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
