name: debarrioapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
#pe.acchiwan.debarrio
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  animated_splash_screen: ^1.0.1+2

  intro_slider:

  intl: ^0.17.0

  google_fonts: ^1.1.1

  otp_text_field: ^1.0.1

  autocomplete_textfield: ^1.7.3

  carousel_slider: ^2.3.1

  modal_bottom_sheet: ^0.2.2

  dropdown_formfield: ^0.1.3

  date_time_picker: ^2.0.0

  syncfusion_flutter_calendar: ^18.3.47

  google_maps_flutter: ^1.0.6

  flutter_svg: ^0.21.0-nullsafety.0

  location: ^3.0.0

  hexcolor: ^1.0.6

  loading_overlay: ^0.2.1

  loading_indicator: ^1.2.0

  shared_preferences: ^0.5.6+2

  permission_handler: ^5.0.1+1

  firebase_auth: ^0.16.1

  cloud_firestore: ^0.13.7

  firebase_storage: ^3.1.6

  firebase_messaging: 6.0.15

  firebase_core: ^0.4.5

  provider: ^4.3.2+2

  geocoder: ^0.2.1

  uuid: ^2.2.2

  geodesy: ^0.3.2

  fluttertoast: ^7.1.5

  auto_suggestion_text_field: ^0.1.1

  geolocator: ^6.1.10

  simple_autocomplete_formfield: ^0.2.7

  image_picker: ^0.6.3+4

  charcode: ^1.1.3

  easy_loader: ^1.0.3

  dots_indicator: ^1.2.0

  sailor: ^0.7.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans_Regular.ttf
        - asset: fonts/OpenSans/OpenSans_Italic.ttf
        - asset: fonts/OpenSans/OpenSans_Bold.ttf
        - asset: fonts/OpenSans/OpenSans_Light.ttf
        - asset: fonts/OpenSans/OpenSans_SemiBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
