import 'package:flutter/painting.dart';

const Color BLACK_DARK = const Color(0xFF101010);
const Color RED_DARK = const Color(0xFFCD402A);
const Color RED_LIGHT = const Color(0xFFFFE5E1);
const Color RED = const Color(0xFFE84A31);
const Color BLUE_LIGHT_2 = const Color(0xFFE3E9F7);
const Color BLUE_LIGHT = const Color(0xFFE9F3FF);
const Color BLUE = const Color(0xFF4A90E2);
const Color YELLOW_LIGHT = const Color(0xFFFAF3E8);
const Color YELLOW = const Color(0xFFFBCC42);
const Color GREEN_DARK = const Color(0xFF58A86E);
const Color GREEN_LIGHT = const Color(0xFFE8FAF2);
const Color GREEN = const Color(0xFF52D176);
const Color WHITE = const Color(0xFFFFFFFF);
const Color GRAY_8 = const Color(0xFFFBFCFC);
const Color GRAY_7 = const Color(0xFFBFBFBF);
const Color GRAY_6 = const Color(0xFFEFF0F2);
const Color GRAY_5 = const Color(0xFFF2F2F2);
const Color GRAY_4 = const Color(0xFFE3ECEE);
const Color GRAY_3 = const Color(0xFFE3E3E3);
const Color GRAY_2 = const Color(0xFF849299);
const Color GRAY_1 = const Color(0xFF4C6072);
const Color BLACK = const Color(0xFF333333);
